# Empty listen_addresses to use systemd socket activation
listen_addresses = ['0.0.0.0:35353']
server_names = ['cloudflare', 'cloudflare-ipv6', 'google', 'google-ipv6']

ipv4_servers = true
ipv6_servers = true
block_ipv6 = false
dnscrypt_servers = true
doh_servers = true
require_dnssec = true
require_nolog = false
require_nofilter = true

forwarding_rules = "/etc/dnscrypt-proxy/forwarding-rules.txt"

[query_log]
  file = '/var/log/dnscrypt-proxy/query.log'

[nx_log]
  file = '/var/log/dnscrypt-proxy/nx.log'

[sources]
  [sources.'public-resolvers']
  url = 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md'
  cache_file = '/var/cache/dnscrypt-proxy/public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''
